### ISSUE TITLE
Unable to make it works with current version on newsplus from playstore

### ISSUE THREAD

**Issue by twidi** [asafge/PocketPlus#10]
Hi. 

On my Nexus 5, I cannot make your plug-in work at all. When I select it in the app, I am redirected on the previous extension I was on. 

It didn't ask for my pocket credentials, nothing. 

Notes that I purged all data from the Android settings for the app and your plug-in, removed them from the play store, and reinstalled them, without more success. 

Could you help? 

Thanks in advance.

**Comment by asafge** [comment]
Hey,
Sometimes the OAuth approval process doesn't start, and we're not sure why. So it's a good idea to try it a few times. Other than that, let's see if there's something in the logs - there's a "send feedback" menu item in Pocket+, try emailing me the log.

**Comment by asafge** [comment]
Closing due to no response from the user.
