### ISSUE TITLE
Not working on Android 5 or 6

### ISSUE THREAD

**Issue by punassuming** [asafge/PocketPlus#11]
I don't know if it is the Android version or the pocket API changes,  but pocket plus has not been working for me for at least half a year.  Is there any chance I can help debug this? 

News+ version: 0.4.0
Device model: Nexus 7
Firmware version: 6.0.1
Kernel version: 3.4.0-gd6b4cbf
nate@BuildMachine-MS-7693 )
#1 SMP PREEMPT Wed Feb 3 07:42:08 EST 2016

Build number: MMB29U

```
--------- beginning of main 03-13 10:25:40.372 W/System (11866): ClassLoader referenced unknown path: /data/app/com.asafge.pocketplus-1/lib/arm 03-13 10:25:47.417 E/Test (11866): LoginActivit.onCreate: null 03-13 10:25:49.412 E/Test (11866): LoginActivit.onCreate: null
```

**Comment by punassuming** [comment]
And as soon as I write this,  the Auth screen came up.   =)  Sorry.

**Comment by madamiub** [comment]
I'm having this issue as well. I've tried refreshing the app and plugin multiple times.

Nexus 6 on 6.0.1
