### ISSUE TITLE
"Keep as unread" by default

### ISSUE THREAD

**Issue by Mosrite** [asafge/PocketPlus#8]
The pocket web app keeps articles as unread as long as I don't explicitly and manually mark them as read. Even if I open a link it won't be marked as read as long as I don't do this manually. As I don't always read an article at once or I sometimes want to look something up later I really like this behaviour.
I think it would be great if PocketPlus would react the same, i.e. if "keep as unread" would be checked by default for every new article.

**Comment by asafge** [comment]
This is more of a News+ issue than a Pocket+ issue. I think you should reopen this here https://github.com/noinnion/newsplus
