### ISSUE TITLE
Allow viewing of archived items

### ISSUE THREAD

**Issue by camdecoster** [asafge/PocketPlus#9]
I'd like to be able to view my archived items from Pocket in News+. Is this possible with the API? A few more comments:
- I probably wouldn't want to cache these items though. Could this feature be turned off for the archived items?
- It would be nice to move items out of the archive and into My List

**Comment by noinnion** [comment]
pls contact the developer of the extension
https://github.com/asafge/pocketplus

**Comment by asafge** [comment]
Hey @camdecoster,
Sorry for the late response, Github didn't notify me in any way about this issue.

It's possible to sync archived items (check out the extension's main screen). The rest of your requests actually depend more on the News+ API, which (I think) has to remain generic enough to support all extensions.

**Comment by camdecoster** [comment]
Having access to the archived items will work for me. I missed that option until now. Thanks for the tip.
